---
- hosts: cent
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    likar
#  vars:
#    users:
#      - vasya
#      - petya
#      - oleg
  roles:
    - role: users
