---
- hosts: cent
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    likar
  tasks:
    name: Смотрим сколько пользователей
      find:
        path: /users
        file_type: directory
      register: users
    name: Создаём пользователей с ключами
        user:
          name: "{{ item }}"
          generate_ssh_key: yes
          ssh_key_bits: 2048
          ssh_key_file: .ssh/id_rsa
          with_items: users
    name: Делаем пользователя СУПЕРПОЛЬЗОВАТЕЛЕМ
      lineinfile:
        path: /etc/sudoers
        regexp: '^root    ALL=(ALL)       ALL'
        insertafter: 'root'
        line: '"{{ item }}"    ALL=(ALL) NOPASSWD:      ALL'
        state: present
        with_items: users
    name: Копируем ключи в папки
      fetch:
        src: /home/"{{ item }}"/.ssh/id_rsa
        dest: /"{{ item }}"/id_rsa.pub
        with_items: user