---
- name: Смотрим сколько пользователей
  find:
    path: /users
    file_type: directory
  register: users
- name: Копируем ключи в папки
  fetch:
    src: /home/"{{ item.name }}"/.ssh/id_rsa
    dest: /"{{ item.name }}"/id_rsa.pub
    with_items: user_details