---
- name: Смотрим сколько пользователей3
  find:
    path: /users
    file_type: directory
  register: output
- name: Копируем ключи в папки
  fetch:
    src: /home/{{ item }}/.ssh/id_rsa
    dest: /etc/ansible/git/users/{{ item }}/id_rsa
    flat: yes
  become:
    true
  become_method:
    sudo
  with_items:
  -  pasha
  -  yura
  - artyem