---
# Психанул
- name: Устанавливаем ключи в autorised keys
  authorized_key:
    user: '{{ item }}'
    state: present
    key: "{{ lookup('file', '/home/likar/.ssh/id_rsa.pub') }}"
    # вместо пользователя likar втыкаете своего локального пользователя
#  with_items: "{{ user }}"
#  with_items:
#    - pasha
#    - yura
#    - artyem