---
#- name: Смотрим сколько пользователей1
#  find:
#     paths: /users
#     file_type: directory
#  register: output

- name: Создаём пользователей с ключами
  user:
     name: "{{ name.user }}"
     generate_ssh_key: yes
     ssh_key_bits: 2048
     ssh_key_file: /home/{{ name.user }}/.ssh/id_rsa
#  with_items:
#     - pasha
#     - yura
#     - artyem