---
#- name: Смотрим сколько пользователей1
#  find:
#     paths: /users
#     file_type: directory
#  register: output

- name: Создаём пользователей с ключами
  user:
     name: "{{ item.name }}"
     generate_ssh_key: yes
     ssh_key_bits: 2048
     ssh_key_file: /home/{{ item.name }}/.ssh/id_rsa
  with_items: "{{ users }}"
#  with_items:
#     - pasha
#     - yura
#     - artyem