---
#- name: Смотрим сколько пользователей1
#  find:
#     paths: /users
#     file_type: directory
#  register: output
- name: vars
  set_fact: user={{ users }}
- name: Создаём пользователей с ключами
  debug:
    msg: "{{ item }}"
  with_items: user
#  user:
#     name: "{{ item.name }}"
#     generate_ssh_key: yes
#     ssh_key_bits: 2048
#     ssh_key_file: /home/{{ item.name }}/.ssh/id_rsa
#  with_items:
#     - pasha
#     - yura
#     - artyem