---
- name: Создаём пользователей с ключами
  user: vars
    name: "{{ user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /home/{{ user }}/.ssh/id_rsa
#  with_items: "{{ user }}"
#  with_items:
#     - pasha
#     - yura
#     - artyem