---
#- name: Смотрим сколько пользователей1
#  find:
#     paths: /users
#     file_type: directory
#  register: output
#- name: Тестирую
#  debug:
#    msg: "{{ item }}"
#  with_items: "{{ user }}"
- name: Создаём пользователей с ключами
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /home/{{ item }}/.ssh/id_rsa
  with_items: "{{ user }}"
#  with_items:
#     - pasha
#     - yura
#     - artyem