---
# - name: Смотрим сколько пользователей
#   find:
#    paths: /users
#    file_type: directory
#   register: users
# Психанул
 - import_tasks: create.yml
# - import_tasks: root.yml
# - import_tasks: copy.yml
