---
# - name: Смотрим сколько пользователей
#   find:
#    paths: /users
#    file_type: directory
#   register: users
# Психанул
#- name: vars
#- include_vars:
#   dir: vars
#   name: item
- import_tasks: create.yml
# - import_tasks: root.yml
# - import_tasks: copy.yml
