---
# - name: Смотрим сколько пользователей
#   find:
#    paths: /users
#    file_type: directory
#   register: users
# Психанул
 - import_tasks: create.yml
   include_vars: vars.yml
 - import_tasks: root.yml
   include_vars: vars.yml
 - import_tasks: copy.yml
   include_vars: vars.yml