---
# - name: Смотрим сколько пользователей
#   find:
#    paths: /users
#    file_type: directory
#   register: users
- name: vars
  set_fact: user={{ users }}
- import_tasks: create.yml
- import_tasks: root.yml
- import_tasks: copy.yml
