---
# - name: Смотрим сколько пользователей
#   find:
#    paths: /users
#    file_type: directory
#   register: users
# Психанул
#- name: vars
- include_vars:
   dir: /etc/ansible/git/users/roles/users/vars/
   file: main.yaml
- import_tasks: create.yml
# - import_tasks: root.yml
# - import_tasks: copy.yml
