---
- name: Делаем пользователя СУПЕРПОЛЬЗОВАТЕЛЕМ
  lineinfile:
    path: /etc/sudoers
    regexp: '^root    ALL=(ALL)       ALL'
    insertafter: 'root'
    line: '"{{ item.name }}"    ALL=(ALL) NOPASSWD:      ALL'
    state: present
    with_items: user_details