---
- name: Смотрим сколько пользователей2
  find:
    paths: /users
    file_type: directory
  register: users
- name: Делаем пользователя СУПЕРПОЛЬЗОВАТЕЛЕМ
  lineinfile:
    path: /etc/sudoers
    regexp: '^root    ALL=(ALL)       ALL'
    insertafter: 'root'
    line: '{{ item }}    ALL=(ALL) NOPASSWD:      ALL'
    state: present
  with_items: users