---
- name: Делаем пользователя СУПЕРПОЛЬЗОВАТЕЛЕМ
  lineinfile:
    path: /etc/sudoers
    regexp: '^root    ALL=(ALL)       ALL'
    insertafter: 'root    ALL=(ALL)       ALL'
    line: '{{ item }}    ALL=(ALL) NOPASSWD:      ALL'
    state: present
#  with_items: "{{ user }}"
#  with_items:
#  - pasha
#  - yura
#  - artyem