---
- name: Делаем пользователя СУПЕРПОЛЬЗОВАТЕЛЕМ
  lineinfile:
    path: /etc/sudoers
    regexp: '^root    ALL=(ALL)       ALL'
    insertafter: 'root'
    line: '{{ item }}    ALL=(ALL) NOPASSWD:      ALL'
    state: present
    with_items: {{ output }}