---
#- name: Смотрим сколько пользователей2
#  find:
#    paths: /users
#    file_type: directory
#  register: output
- name: Делаем пользователя СУПЕРПОЛЬЗОВАТЕЛЕМ
  lineinfile:
    path: /etc/sudoers
    regexp: '^root    ALL=(ALL)       ALL'
    insertafter: 'root    ALL=(ALL)       ALL'
    line: '{{ item }}    ALL=(ALL) NOPASSWD:      ALL'
    state: present
  vars_file: vars
#  with_items:
#  - pasha
#  - yura
#  - artyem