- name: Установка питона
  pip:
    name: docker
    state: latest
- name: Добавление записи в репозиторий
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
- name: Update apt and install docker-ce
  yum:
    update_cache: yes
    name: docker-ce
    state: latest
