- name: Устанавливаем Docker
  yum:
    name: docker
- name: Устанавливаем Python pip
  yum:
    name: python3-pip
    state: installed
- name: Устанавливаем Python
  pip:
    name: docker
- import_tasks: systemctl.yml
- import_tasks: image.yml