#- name: Устанавливаем Docker
#  yum:
#    name: docker
#- name: Add Docker GPG apt Key
#  apt_key:
#      url: https://download.docker.com/linux/ubuntu/gpg
#      state: present
- name: Add Docker Repository
  yum_repository:
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    state: present
- name: Update apt and install docker-ce
  yum:
   update_cache: yes
   name: docker-ce
   state: latest
- name: Install Docker Module for Python
  pip:
    name: docker
- import_tasks: systemctl.yml
- import_tasks: image.yml